### ISSUE TITLE
cargo check unexpectedly fails with status 101

### ISSUE THREAD

**Issue by kornelski** [google/rerast#15]
On some projects, like https://github.com/tomaka/glutin rerast fails during `cargo check` phase, even though `cargo check` run without rerast works fine:

```sh
cargo +nightly rerast --rules_file=../rules.rs --force --verbose
```

> Running cargo check in order to build dependencies and get rustc commands
> cargo check failed (exit code = 101). Output follows:
> RERAST_JSON_MARKER: [["…lots of normal output here, no mention of errors…"}]

This is surprising, because `cargo check` alone seems to work fine (it's even cached from rerast's run):

```
$ cargo check
    Finished dev [unoptimized + debuginfo] target(s) in 0.16 secs
$ echo $?
0
```

**Comment by davidlattimore** [comment]
Thanks for the report. Looks like this is the failure:
error: couldn't read "/home/david/src/glutin/target/debug/deps/egl_bindings.rs": No such file or directory (os error 2)
  --> src/api/egl/ffi.rs:22:5
   |
22 |     include!(concat!(env!("OUT_DIR"), "/egl_bindings.rs"));
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

**Comment by kornelski** [comment]
So that's related to #9. 

`OUT_DIR` is not `--out-dir` unfortunately.

It's set only when there's `build.rs` involved. 

```rust
cmd.arg("--out-dir").arg(&cx.files().out_dir(unit));
```
vs

```
cmd.env("OUT_DIR", &cx.files().build_script_out_dir(&dep));
```

fn build_script_out_dir = 

```
let dir = self.pkg_dir(unit);
        self.layout(unit.kind).build().join(dir).join("out")
```

**Comment by kornelski** [comment]
wrap.sh:

```sh
echo "OUT_DIR = $OUT_DIR" >&2
rustc "${@:2}"
```

Seems to work with:

```sh
RUSTC_WRAPPER=./wrap.sh cargo check
```

> OUT_DIR = /www/glutin/target/debug/build/glutin-0a23855397346a02

**Comment by kornelski** [comment]
Yes, I've seen it too. The message sounds like it's a problem with incremental compilation Rust.  It goes away when I run it again.

**Comment by kornelski** [comment]
But the main problem is fixed! 🙌

**Comment by kornelski** [comment]
cc #17
