### ISSUE TITLE
Intermittent panics in rustc related to incremental compilation

### ISSUE THREAD

**Issue by davidlattimore** [google/rerast#17]
Seen when running rerast on glutin. @kornelski suggested it's due to incremental compilation, and indeed setting CARGO_INCREMENTAL=0 seems to stop it. Not sure if it's a bug in incremental compilation or just an incompatibility between the way we're using rustc and incremental compilation.

thread 'main' panicked at 'Forcing query with already existing DepNode.

query-key: ParamEnvAnd { param_env: ParamEnv { caller_bounds: Slice([]), reveal: UserFacing }, value: unsafe extern "rust-intrinsic" fn(*const std::os::raw::c_void) -> extern "system" fn(u32, i32, *mut i32) {std::intrinsics::transmute::<*const std::os::raw::c_void, extern "system" fn(u32, i32, *mut i32)>} }
dep-node: IsCopy(7cbec90d2168a3bd-88dbb5e68c554118)', librustc/ty/maps/mod.rs:97:1
stack backtrace:
0: std::sys::unix::backtrace::tracing:imp:unwind_backtrace
at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
1: std::sys_common::backtrace::print
at libstd/sys_common/backtrace.rs:71
at libstd/sys_common/backtrace.rs:59
2: std::panicking::default_hook::{{closure}}
at libstd/panicking.rs:206
3: std::panicking::default_hook
at libstd/panicking.rs:222
4: rustc::util::common::panic_hook
5: std::panicking::rust_panic_with_hook
at libstd/panicking.rs:401
6: std::panicking::begin_panic_fmt
at libstd/panicking.rs:347
7: rustc::ty::maps::<impl rustc::ty::maps::queries::is_copy_raw<'tcx>>::force_with_lock
8: rustc::ty::maps::<impl rustc::ty::maps::queries::is_copy_raw<'tcx>>::try_get
9: rustc::ty::maps::TyCtxtAt::is_copy_raw
10: rustc::middle::mem_categorization::MemCategorizationContext::type_moves_by_default
11: rustc::middle::expr_use_visitor::ExprUseVisitor::consume_expr
12: rustc::middle::expr_use_visitor::ExprUseVisitor::walk_expr
13: rustc::middle::expr_use_visitor::ExprUseVisitor::walk_expr
14: rustc::middle::expr_use_visitor::ExprUseVisitor::walk_expr
15: <rustc_passes::rvalue_promotion::CheckCrateVisitor<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_nested_body
16: rustc_passes::rvalue_promotion::rvalue_promotable_map
17: rustc::dep_graph::graph::DepGraph::with_task_impl
18: rustc::ty::context::tls::with_related_context
19: rustc::ty::maps::<impl rustc::ty::maps::queries::rvalue_promotable_map<'tcx>>::force_with_lock
20: rustc::ty::maps::<impl rustc::ty::maps::queries::rvalue_promotable_map<'tcx>>::try_get
21: rustc::ty::maps::TyCtxtAt::rvalue_promotable_map
22: rustc::ty::maps::<impl rustc::ty::context::TyCtxt<'a, 'tcx, 'lcx>>::rvalue_promotable_map
23: rustc_passes::rvalue_promotion::const_is_rvalue_promotable_to_static
24: rustc::dep_graph::graph::DepGraph::with_task_impl
25: rustc::ty::context::tls::with_related_context
26: rustc::ty::maps::<impl rustc::ty::maps::queries::const_is_rvalue_promotable_to_static<'tcx>>::force_with_lock
27: rustc::ty::maps::<impl rustc::ty::maps::queries::const_is_rvalue_promotable_to_static<'tcx>>::try_get
28: rustc::ty::maps::TyCtxtAt::const_is_rvalue_promotable_to_static
29: rustc::ty::maps::<impl rustc::ty::context::TyCtxt<'a, 'tcx, 'lcx>>::const_is_rvalue_promotable_to_static
30: rustc_passes::rvalue_promotion::check_crate
31: rustc::ty::context::tls::enter_context
32: <std::thread::local::LocalKey>::with
33: rustc::ty::context::TyCtxt::create_and_enter
34: rustc_driver::driver::compile_input
35: rustc_driver::run_compiler_impl
36: syntax::with_globals
37: rustc_driver::run_compiler
38: rerast::CompilerInvocationInfo::run_compiler
at src/lib.rs:165
39: rerast::run_compiler
at src/lib.rs:449
40: rerast::RerastCompilerDriver::apply_rules_to_code
at /home/dml/rerast/src/lib.rs:556
41: rerast::RerastCompilerDriver::apply_rules_from_string
at /home/dml/rerast/src/lib.rs:510
42: cargo_rerast::cargo_rerast
at src/bin/cargo-rerast.rs:364
43: cargo_rerast::main
at src/bin/cargo-rerast.rs:451
44: std::rt::lang_start::{{closure}}
at /checkout/src/libstd/rt.rs:74
45: std::panicking::try::do_call
at libstd/rt.rs:59
at libstd/panicking.rs:305
46: __rust_maybe_catch_panic
at libpanic_unwind/lib.rs:101
47: std::rt::lang_start_internal
at libstd/panicking.rs:284
at libstd/panic.rs:361
at libstd/rt.rs:58
48: std::rt::lang_start
at /checkout/src/libstd/rt.rs:74
49: main
50: __libc_start_main
51: start
query stack during panic:
#0 [rvalue_promotable_map] checking which parts of support::gl::Gles2::GetUniformiv are promotable to static
--> /home/dml/src/glutin/target/debug/build/glutin-7d863af2e66ed1de/out/test_gl_bindings.rs:1734:23
|
1734 | #[inline] pub unsafe fn GetUniformiv(&self, program: types::GLuint, location: types::GLint, params: *mut types::GLint) -> () { __gl_imports::mem::transmute::<, extern "system" fn(types::GLuint, types::GLint, *mut types::GLint) -> ()>(self.GetUniformiv.f)(program, location, params) }
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#1 [const_is_rvalue_promotable_to_static] const checking if rvalue is promotable to static support::gl::Gles2::GetUniformiv
--> /home/dml/src/glutin/target/debug/build/glutin-7d863af2e66ed1de/out/test_gl_bindings.rs:1734:23
|
1734 | #[inline] pub unsafe fn GetUniformiv(&self, program: types::GLuint, location: types::GLint, params: *mut types::GLint) -> () { __gl_imports::mem::transmute::<_, extern "system" fn(types::GLuint, types::GLint, *mut types::GLint) -> ()>(self.GetUniformiv.f)(program, location, params) }
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
end of query stack

**Comment by michaelwoerister** [comment]
Could you open an issue in the main Rust repository?

**Comment by kornelski** [comment]
https://github.com/rust-lang/rust/issues/50178

**Comment by michaelwoerister** [comment]
Thanks!
