### ISSUE TITLE
Macros are lost when compiling nickel.rs

### ISSUE THREAD

**Issue by kornelski** [google/rerast#18]
@davidlattimore, you're on a roll! Here's another one: https://github.com/nickel-org/nickel.rs

> warning: unused `#[macro_use]` import
 --> examples/https.rs:1:1
  |
1 | #[macro_use] extern crate nickel;
  | ^^^^^^^^^^^^
  |
  = note: #[warn(unused_imports)] on by default

> error: cannot find macro `lazy_static!` in this scope
   --> examples/integration_testing.rs:279:9
    |
279 |         lazy_static! {
    |         ^^^^^^^^^^^

> error: cannot find macro `middleware!` in this scope
  --> examples/integration_testing.rs:81:21
   |
81 |     server.get("/", middleware!( "Hello World" ));
   |                     ^^^^^^^^^^

**Comment by davidlattimore** [comment]
Thanks. It's great to see it being used and getting the issues ironed out.

I'm able to reproduce this by running "cargo check --tests".

Rerast currently runs: "cargo check -j 1 -v --tests --benches --examples".

I've been thinking I'd like to give the user some control over which targets get built, but have been unsure about how best to expose that and what to have as the default.

**Comment by kornelski** [comment]
I was comparing it to plain `cargo check`. I can reproduce it with `cargo check --tests`, so it looks like it's just the crate's fault.

**Comment by davidlattimore** [comment]
You can now pass --targets lib to rerast and it'll only pass --lib to cargo check. With this option, nickel.rs can be processed - just not those tests. In the process of testing on nickel.rs I discovered #19 (now fixed).
