### ISSUE TITLE
Rerast requires `rustup`

### ISSUE THREAD

**Issue by arilotter** [google/rerast#29]
When using a nightly rust outside of `rustup`, `rerast` fails to compile because `RUSTUP_HOME` and `RUSTUP_TOOLCHAIN` aren't defined.

**Comment by davidlattimore** [comment]
Thanks for reporting that. I've added an alternative mechanism for determining the Rust sysroot directory. It appears to work, although I didn't actually uninstall rustup, so can't be entirely sure. I'd be interested to hear if it works for you. Oh, I also updated the code work with rustc 2019-11-11.

**Comment by arilotter** [comment]
I get further than last time!
My setup might be extra-weird, since I use NixOS, which doesn't tend to have binaries in places you'd assume. How can I help you debug this? :)
```bash
$ rustc --version
rustc 1.40.0-nightly (4f03f4a98 2019-11-12)

$ cargo install rerast
...
error[E0463]: can't find crate for `rustc`
  --> /home/ari/.cargo/registry/src/github.com-1ecc6299db9ec823/rerast-0.1.73/src/lib.rs:77:1
   |
77 | extern crate rustc;
   | ^^^^^^^^^^^^^^^^^^^ can't find crate
```

**Comment by bjorn3** [comment]
`rustup component add rustc-dev` should fix this. Rust recently split the compiler internal rlibs out of the rust-std component.

**Comment by arilotter** [comment]
Worked perfectly, thanks @bjorn3 !
