### ISSUE TITLE
Specifying type () in placeholders generates bad syntax

### ISSUE THREAD

**Issue by joshtriplett** [google/rerast#37]
Specifying placeholders containing the unit type `()` causes rerast to generate incorrect syntax:

```
 cargo +nightly rerast --diff -p 'x: bool, y: ()' -s 'x' -r 'x'
error: error: expected one of `(` or `<`, found `:`
 --> src/__rerast_rules.rs:1:13
  |
1 | pub fn rulex: bool, y: (){replace!(x => x);}
  |             ^ expected one of `(` or `<`
```

rerast seems to have left out the parentheses around the placeholders.

**Comment by davidlattimore** [comment]
Thanks Josh. The -p argument takes two different forms, one with parenthesis, which is primarily used when there's generics. e.g. -p '<T: Clone>(a: T)' and one where generics aren't used, which allows you to skip the parenthesis. The code for determining which form was a little too simplistic.

If you need a workaround until the next release, you can add the parenthesis explicitly, e.g. -p '(x: bool, y: ())'

**Comment by joshtriplett** [comment]
Thanks for the fix! And thank you for the suggested workaround, but I can easily just build from git to get the fixed version.
