### ISSUE TITLE
can't compile on latest nightly

### ISSUE THREAD

**Issue by mimoo** [google/rerast#43]
Getting this error:

```
error[E0609]: no field `kind` on type `rustc_middle::ty::subst::GenericArg<'_>`
   --> /Users/davidwg/.cargo/registry/src/github.com-1ecc6299db9ec823/rerast-0.1.90/src/change_to_rule.rs:387:48
    |
387 |             if let TyKind::Param(..) = subtype.kind {
    |                                                ^^^^ unknown field

error: aborting due to previous error
```

I've also managed to compile with `nightly-2020-04-06` and getting errors like this when I try to use the tool:

```
thread 'main' panicked at 'assertion failed: self.host', src/tools/cargo/src/cargo/core/profiles.rs:940:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by davidlattimore** [comment]
Sorry, I've got changes to fix the build, but a couple of tests are failing and I haven't yet found time to work out why they're failing.

If you want to try with an older rustc, you can hopefully match up rerast versions to rustc versions by looking through the rerast commit history. e.g. rerast 0.1.89 should hopefully work with nightly-2020-03-02.

**Comment by davidlattimore** [comment]
I fixed compilation on the latest nightly and pushed a new release
